name: Node.js CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app using ssh
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{secrets.PASSWORD}}
          port: 22
          script: |
            cd /commonplace
            git pull origin main
            git status

            cd backend
            npm ci
            /root/.nvm/versions/node/v20.10.0/bin/pm2 restart api
            cd ..

            for arg in frontend admin; do
            cd ${arg}
            rm -r node_modules
            npm ci --legacy-peer-deps
            rm -r build
            npm run build --max_old_space_size=4096
            rm -r /var/www/bubengogh/${arg}/*
            cp -r build/* /var/www/bubengogh/${arg}/
            cd ..;

            done
