name: Node.js CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app using ssh
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{secrets.PASSWORD}}
          port: 22
          script: |
            cd /commonplace
            git pull origin main
            git status

            cd backend
            pm2 restart api
            cd ..

            for arg in frontend admin; do
            cd ${arg}
            npm i --force --no-optional
            npm run build
            rm -r /var/www/bubengogh/${arg}/*
            cp -r build/* /var/www/bubengogh/${arg}/
            cd ..;

            done
